apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    {{- include "pulsecheck.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 8000
      protocol: TCP
  selector:
    {{- include "pulsecheck.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
