apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pulsecheck.fullname" . }}-config
  labels:
    {{- include "pulsecheck.labels" . | nindent 4 }}
data:
  OAUTH_REDIRECT_BASE_URL: {{ .Values.env.oauthRedirectBaseUrl | quote }}
  FRONTEND_URL: {{ .Values.env.frontendUrl | quote }}
