apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "pulsecheck.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: 6379
      protocol: TCP
  selector:
    {{- include "pulsecheck.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
