apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pulsecheck.fullname" . }}-secrets
  labels:
    {{- include "pulsecheck.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ required "secrets.postgresPassword is required" .Values.secrets.postgresPassword | quote }}
  SECRET_KEY: {{ required "secrets.secretKey is required" .Values.secrets.secretKey | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | quote }}
  GITHUB_CLIENT_ID: {{ .Values.secrets.githubClientId | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.secrets.githubClientSecret | quote }}
  DATABASE_URL: "postgresql://{{ .Values.postgres.auth.username }}:{{ .Values.secrets.postgresPassword }}@postgres:{{ .Values.postgres.service.port }}/{{ .Values.postgres.auth.database }}"
  REDIS_URL: "redis://redis:{{ .Values.redis.service.port }}/0"
